### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mzhaodev**

### CODE REVIEW

**Comment by io12** [comment]
Very cool, but too laggy. Asciicinema doesn't seem well suited to high framerate games. I'd add a gif but that would be too distracting.

**Comment by io12** [comment]
Very cool, but too laggy. Asciicinema doesn't seem well suited to high framerate games. I'd add a gif but that would be too distracting.

**Comment by eragonfan125** [comment]
Why won't you pick up the phone?

**Comment by eragonfan125** [comment]
Also, its not laggy at all on the computer (I'm guessing you are using your phone?).

**Comment by io12** [comment]
No, it is laggy

**Comment by eragonfan125** [comment]
WHY WON'T YOU PICK UP THE PHONE?

**Pull request closed without merging**
